<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * soortactiviteitenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoortactiviteitRepository extends EntityRepository
{

}
